package View;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Produto;
import DAO.ProdutoDAO;
import DAO.ClienteDAO;
import DAO.VendedorDAO;
import DAO.VendaDAO;
import Model.Cliente;
import Model.Vendedor;
import Model.Venda;
import Model.ItensVenda;
import Utils.RelatorioPDF;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class ViewVendaConsulta extends javax.swing.JInternalFrame {
    ArrayList<Produto> listaModelProdutos;
    String salvarAlterar;
    Produto produto; 
    ProdutoDAO produtoDAO; 
    
    ArrayList<Cliente> listaModelClientes;
    Cliente cliente; 
    ClienteDAO clienteDAO; 
    
    ArrayList<Vendedor> listaModelVendedores;
    Vendedor vendedor; 
    VendedorDAO vendedorDAO; 
    
    ItensVenda itensVenda; 
    Venda venda;
    VendaDAO vendaDAO;
    
    public ViewVendaConsulta() {
        produtoDAO = new ProdutoDAO();
        clienteDAO = new ClienteDAO();
        vendedorDAO = new VendedorDAO();
        vendaDAO = new VendaDAO();
        venda = new Venda();
        produto = new Produto();
        vendedor = new Vendedor();
        cliente = new Cliente();
        
        listaModelVendedores = new ArrayList<>();
        listaModelClientes = new ArrayList<>();
        listaModelProdutos = new ArrayList<>();
        
        initComponents();
        this.setVisible(true);
        
        //this.carregarProdutos();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idCLiente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_cliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_idVenda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_venda = new javax.swing.JTable();
        btn_BuscarVendaPorId = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_idVendedor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_vendedor = new javax.swing.JTextField();
        label_TotVenda = new javax.swing.JLabel();
        label_TotVenda1 = new javax.swing.JLabel();
        btn_PDF = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Vendedor");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cliente");

        jLabel3.setText("ID");

        txt_idCLiente.setEditable(false);
        txt_idCLiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idCLienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome");

        txt_cliente.setEditable(false);
        txt_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_clienteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Venda");

        jLabel6.setText("ID");

        txt_idVenda.setEditable(false);
        txt_idVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idVendaActionPerformed(evt);
            }
        });

        tb_venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_vendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_venda);

        btn_BuscarVendaPorId.setText("Buscar venda por código");
        btn_BuscarVendaPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarVendaPorIdActionPerformed(evt);
            }
        });

        jLabel11.setText("ID");

        txt_idVendedor.setEditable(false);
        txt_idVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idVendedorActionPerformed(evt);
            }
        });

        jLabel12.setText("Nome");

        txt_vendedor.setEditable(false);
        txt_vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vendedorActionPerformed(evt);
            }
        });

        label_TotVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_TotVenda.setForeground(new java.awt.Color(51, 153, 255));

        label_TotVenda1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_TotVenda1.setForeground(new java.awt.Color(51, 153, 255));
        label_TotVenda1.setText("Total R$");

        btn_PDF.setText("Gerar PDF");
        btn_PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_idCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_idVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                                .addGap(306, 306, 306))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_idVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_vendedor))))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_TotVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(btn_BuscarVendaPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_TotVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_PDF, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_idVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_idVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txt_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_idCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_BuscarVendaPorId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_TotVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(btn_PDF)
                    .addComponent(label_TotVenda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vendedorActionPerformed

    private void txt_idVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idVendedorActionPerformed

    private void btn_BuscarVendaPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarVendaPorIdActionPerformed
        limparCampos();
        String id = JOptionPane.showInputDialog(this, "Digite o código da venda:");
        if (id == null || id.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Você deve informar um código válido!", "Validação de dados!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!id.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "O código deve conter apenas números!", "Validação de dados!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            //vendedor = new Vendedor();
            //cliente = new Cliente();
            venda = vendaDAO.BuscarVendaPorId(id);
            if (venda == null) {
                JOptionPane.showMessageDialog(this, "Código de venda não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                // Preencher os campos corretamente
                txt_idVenda.setText(String.valueOf(venda.getId()));
                txt_idCLiente.setText(String.valueOf(venda.getCliente().getIdCliente()));
                txt_idVendedor.setText(String.valueOf(venda.getVendedor().getId()));
                txt_cliente.setText(venda.getCliente().getCliNome());
                txt_vendedor.setText(venda.getVendedor().getNome());
                label_TotVenda.setText(String.valueOf(venda.getTotalVenda()));

                // Chamar a atualização da tabela
                atualizaTabelaItens();
            }
        } catch (Exception e) {
            Logger.getLogger(ViewProdutoConsulta.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Erro ao buscar venda: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_BuscarVendaPorIdActionPerformed

    private void tb_vendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_vendaMouseClicked

    }//GEN-LAST:event_tb_vendaMouseClicked

    private void txt_idVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idVendaActionPerformed

    private void txt_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_clienteActionPerformed

    private void txt_idCLienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idCLienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idCLienteActionPerformed

    private void btn_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PDFActionPerformed
         if (venda == null) {
            JOptionPane.showMessageDialog(this, "Nenhuma venda selecionada!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Cria o JFileChooser
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Salvar Relatório como PDF");

        // Define o filtro para exibir apenas arquivos PDF
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos PDF (*.pdf)", "pdf");
        fileChooser.setFileFilter(filter);

        // Sugere um nome padrão para o arquivo
        String nomePadrao = "relatorio_venda_" + venda.getId() + ".pdf";
        fileChooser.setSelectedFile(new java.io.File(nomePadrao));

        // Exibe o diálogo para salvar o arquivo
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            // Obtém o caminho selecionado pelo usuário
            java.io.File arquivoSelecionado = fileChooser.getSelectedFile();

            // Garante que o arquivo tenha a extensão .pdf
            String caminhoArquivo = arquivoSelecionado.getAbsolutePath();
            if (!caminhoArquivo.toLowerCase().endsWith(".pdf")) {
                caminhoArquivo += ".pdf";
            }

            // Gera o relatório
            RelatorioPDF.gerarRelatorioVenda(venda, caminhoArquivo);

            // Exibe mensagem de sucesso
            JOptionPane.showMessageDialog(this, "Relatório gerado com sucesso!\nCaminho: " + caminhoArquivo, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_PDFActionPerformed

    private void limparCampos() {
        txt_idVenda.setText("");
        txt_idCLiente.setText("");
        txt_idVendedor.setText("");
        txt_cliente.setText("");
        txt_vendedor.setText("");
        label_TotVenda.setText("");
        limparTabela();
    }
    
    private void limparTabela() {
        // Cria um novo DefaultTableModel vazio com as mesmas colunas
        String[] colunas = {"Produto", "Quantidade", "Preço Unit", "Preço Total"};
        DefaultTableModel modeloVazio = new DefaultTableModel(new Object[][]{}, colunas);

        // Define o novo modelo vazio para a tabela
        tb_venda.setModel(modeloVazio);
    }
    
    public void atualizaTabelaItens() 
    {
        String[][] dados = new String[venda.getItensVenda().size()][4];
        int i = 0;
        for (ItensVenda iv : venda.getItensVenda()) {
            dados[i][0] = iv.getProduto().getNome();
            dados[i][1] = String.valueOf(iv.getQuantidade());
            dados[i][2] = String.valueOf(iv.getPreco());
            dados[i][3] = String.valueOf(iv.getPrecototalitem());
            i++;
        }

        String[] tituloColuna = {"Produto", "Quantidade", "Preço Unit", "Preço Total"};

        DefaultTableModel tabelaItens = new DefaultTableModel(dados, tituloColuna) {
            boolean[] canEdit = new boolean[]{false, false, false, false};

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        tb_venda.setModel(tabelaItens);
        tb_venda.getColumnModel().getColumn(0).setPreferredWidth(300);
        tb_venda.getColumnModel().getColumn(1).setPreferredWidth(300);
        tb_venda.getColumnModel().getColumn(2).setPreferredWidth(300);
        tb_venda.getColumnModel().getColumn(3).setPreferredWidth(300);

        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        tb_venda.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        tb_venda.setRowHeight(25);
        tb_venda.updateUI();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuscarVendaPorId;
    private javax.swing.JButton btn_PDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_TotVenda;
    private javax.swing.JLabel label_TotVenda1;
    private javax.swing.JTable tb_venda;
    private javax.swing.JTextField txt_cliente;
    private javax.swing.JTextField txt_idCLiente;
    private javax.swing.JTextField txt_idVenda;
    private javax.swing.JTextField txt_idVendedor;
    private javax.swing.JTextField txt_vendedor;
    // End of variables declaration//GEN-END:variables
}
