package View;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Produto;
import DAO.ProdutoDAO;
import DAO.ClienteDAO;
import DAO.VendedorDAO;
import DAO.VendaDAO;
import Model.Cliente;
import Model.Vendedor;
import Model.Venda;
import Model.ItensVenda;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

public class ViewVenda extends javax.swing.JInternalFrame {
    ArrayList<Produto> listaModelProdutos;
    String salvarAlterar;
    Produto produto; 
    ProdutoDAO produtoDAO; 
    
    ArrayList<Cliente> listaModelClientes;
    Cliente cliente; 
    ClienteDAO clienteDAO; 
    
    ArrayList<Vendedor> listaModelVendedores;
    Vendedor vendedor; 
    VendedorDAO vendedorDAO; 
    
    ItensVenda itensVenda; 
    Venda venda;
    VendaDAO vendaDAO;
    
    public ViewVenda() {
        produtoDAO = new ProdutoDAO();
        clienteDAO = new ClienteDAO();
        vendedorDAO = new VendedorDAO();
        vendaDAO = new VendaDAO();
        venda = new Venda();
        produto = new Produto();
        vendedor = new Vendedor();
        cliente = new Cliente();
        
        listaModelVendedores = new ArrayList<>();
        listaModelClientes = new ArrayList<>();
        listaModelProdutos = new ArrayList<>();
        
        initComponents();
        this.setVisible(true);
        
        //this.carregarProdutos();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_cliente = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_cliente = new javax.swing.JTable();
        lb_cidade2 = new javax.swing.JLabel();
        txt_filtro = new javax.swing.JTextField();
        btn_selecionar = new javax.swing.JButton();
        dialog_produto = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_produto = new javax.swing.JTable();
        lb_cidade3 = new javax.swing.JLabel();
        txt_filtro2 = new javax.swing.JTextField();
        btn_selecionar2 = new javax.swing.JButton();
        dialog_vendedor = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_vendedor = new javax.swing.JTable();
        lb_cidade4 = new javax.swing.JLabel();
        txt_filtro3 = new javax.swing.JTextField();
        btn_selecionar3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idCLiente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_cliente = new javax.swing.JTextField();
        btn_modalCliente = new javax.swing.JButton();
        txt_descricao = new javax.swing.JTextField();
        btn_modalProduto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_idProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_qte = new javax.swing.JTextField();
        txt_precoUnit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_precoTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_venda = new javax.swing.JTable();
        btn_FinalizarVenda = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_idVendedor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_vendedor = new javax.swing.JTextField();
        btn_modalVendedor = new javax.swing.JButton();
        bt_addProduto = new javax.swing.JButton();
        bt_delProduto = new javax.swing.JButton();
        label_TotVenda = new javax.swing.JLabel();
        label_TotVenda1 = new javax.swing.JLabel();

        dialog_cliente.setMinimumSize(new java.awt.Dimension(600, 700));

        tb_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_clienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_cliente);

        lb_cidade2.setText("Filtrar por nome:");

        txt_filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filtroActionPerformed(evt);
            }
        });
        txt_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_filtroKeyReleased(evt);
            }
        });

        btn_selecionar.setText("Selecionar");
        btn_selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_selecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addComponent(lb_cidade2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_cidade2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_selecionar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialog_clienteLayout = new javax.swing.GroupLayout(dialog_cliente.getContentPane());
        dialog_cliente.getContentPane().setLayout(dialog_clienteLayout);
        dialog_clienteLayout.setHorizontalGroup(
            dialog_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialog_clienteLayout.setVerticalGroup(
            dialog_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        dialog_produto.setMinimumSize(new java.awt.Dimension(600, 700));

        tb_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Preço", "Validade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_produtoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_produto);

        lb_cidade3.setText("Filtrar por nome:");

        txt_filtro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filtro2ActionPerformed(evt);
            }
        });
        txt_filtro2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_filtro2KeyReleased(evt);
            }
        });

        btn_selecionar2.setText("Selecionar");
        btn_selecionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selecionar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_filtro2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_selecionar2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addComponent(lb_cidade3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_cidade3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_filtro2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_selecionar2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialog_produtoLayout = new javax.swing.GroupLayout(dialog_produto.getContentPane());
        dialog_produto.getContentPane().setLayout(dialog_produtoLayout);
        dialog_produtoLayout.setHorizontalGroup(
            dialog_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_produtoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialog_produtoLayout.setVerticalGroup(
            dialog_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_produtoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        dialog_vendedor.setMinimumSize(new java.awt.Dimension(600, 700));

        tb_vendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_vendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_vendedorMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tb_vendedor);

        lb_cidade4.setText("Filtrar por nome:");

        txt_filtro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filtro3ActionPerformed(evt);
            }
        });
        txt_filtro3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_filtro3KeyReleased(evt);
            }
        });

        btn_selecionar3.setText("Selecionar");
        btn_selecionar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selecionar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_filtro3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_selecionar3, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addComponent(lb_cidade4)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_cidade4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_filtro3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_selecionar3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialog_vendedorLayout = new javax.swing.GroupLayout(dialog_vendedor.getContentPane());
        dialog_vendedor.getContentPane().setLayout(dialog_vendedorLayout);
        dialog_vendedorLayout.setHorizontalGroup(
            dialog_vendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_vendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialog_vendedorLayout.setVerticalGroup(
            dialog_vendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_vendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Vendedor");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cliente");

        jLabel3.setText("ID");

        txt_idCLiente.setEditable(false);
        txt_idCLiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idCLienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome");

        txt_cliente.setEditable(false);
        txt_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_clienteActionPerformed(evt);
            }
        });

        btn_modalCliente.setText("Buscar");
        btn_modalCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modalClienteActionPerformed(evt);
            }
        });

        txt_descricao.setEditable(false);
        txt_descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descricaoActionPerformed(evt);
            }
        });

        btn_modalProduto.setText("Buscar");
        btn_modalProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modalProdutoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Produto");

        jLabel6.setText("ID");

        txt_idProduto.setEditable(false);
        txt_idProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idProdutoActionPerformed(evt);
            }
        });

        jLabel7.setText("Descrição");

        jLabel8.setText("Qtde");

        txt_qte.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_qteCaretUpdate(evt);
            }
        });
        txt_qte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qteActionPerformed(evt);
            }
        });

        txt_precoUnit.setEditable(false);
        txt_precoUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precoUnitActionPerformed(evt);
            }
        });

        jLabel9.setText("Preço Unit");

        jLabel10.setText("Preço Total");

        txt_precoTotal.setEditable(false);
        txt_precoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precoTotalActionPerformed(evt);
            }
        });

        tb_venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_vendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_venda);

        btn_FinalizarVenda.setText("Finalizar Venda");
        btn_FinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FinalizarVendaActionPerformed(evt);
            }
        });

        jLabel11.setText("ID");

        txt_idVendedor.setEditable(false);
        txt_idVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idVendedorActionPerformed(evt);
            }
        });

        jLabel12.setText("Nome");

        txt_vendedor.setEditable(false);
        txt_vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vendedorActionPerformed(evt);
            }
        });

        btn_modalVendedor.setText("Buscar");
        btn_modalVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modalVendedorActionPerformed(evt);
            }
        });

        bt_addProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_addProduto.setText("+");
        bt_addProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addProdutoActionPerformed(evt);
            }
        });

        bt_delProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_delProduto.setText("-");
        bt_delProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_delProdutoActionPerformed(evt);
            }
        });

        label_TotVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_TotVenda.setForeground(new java.awt.Color(51, 153, 255));

        label_TotVenda1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_TotVenda1.setForeground(new java.awt.Color(51, 153, 255));
        label_TotVenda1.setText("Total R$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_precoUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_addProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_delProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_idProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_idVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_vendedor)
                                .addGap(18, 18, 18)
                                .addComponent(btn_modalVendedor))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_idCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(251, 251, 251)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_precoTotal))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                            .addComponent(txt_cliente))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_modalCliente)
                                            .addComponent(btn_modalProduto)))))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_TotVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_TotVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_FinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_idVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modalVendedor))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_idCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modalCliente))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_idProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_modalProduto))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txt_precoUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txt_precoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_delProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_addProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_FinalizarVenda)
                            .addComponent(label_TotVenda1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(label_TotVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_clienteMouseClicked

    }//GEN-LAST:event_tb_clienteMouseClicked

    private void txt_filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filtroActionPerformed

    private void txt_filtroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtroKeyReleased
        String filtro = txt_filtro.getText();

                if (filtro.isEmpty()) {
                    carregarClientes("");
                } else {
                    carregarClientes(filtro);
                }
    }//GEN-LAST:event_txt_filtroKeyReleased

    private void btn_selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selecionarActionPerformed
        txt_idCLiente.setText(tb_cliente.getValueAt(tb_cliente.getSelectedRow(), 0).toString());
        txt_cliente.setText(tb_cliente.getValueAt(tb_cliente.getSelectedRow(), 1).toString());
        cliente = new Cliente();
        cliente.setIdCliente(Integer.parseInt(txt_idCLiente.getText()));
        cliente.setCliNome(txt_cliente.getText());
        dialog_cliente.dispose();
    }//GEN-LAST:event_btn_selecionarActionPerformed

    private void tb_produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_produtoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_produtoMouseClicked

    private void txt_filtro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filtro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filtro2ActionPerformed

    private void txt_filtro2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtro2KeyReleased
        // TODO add your handling code here:
        String filtro = txt_filtro2.getText();

        if (filtro.isEmpty()) {
            carregarProdutos("");
        } else {
            carregarProdutos(filtro);
        }
    }//GEN-LAST:event_txt_filtro2KeyReleased

    private void btn_selecionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selecionar2ActionPerformed
        // TODO add your handling code here:
        txt_idProduto.setText(tb_produto.getValueAt(tb_produto.getSelectedRow(), 0).toString());
        txt_descricao.setText(tb_produto.getValueAt(tb_produto.getSelectedRow(), 1).toString());
        txt_precoUnit.setText(tb_produto.getValueAt(tb_produto.getSelectedRow(), 2).toString());
        produto = new Produto();
        produto.setId(Integer.parseInt(txt_idProduto.getText()));
        produto.setNome(txt_descricao.getText());
        produto.setPreco_venda(Double.parseDouble(txt_precoUnit.getText()));        
        
        dialog_produto.dispose();
    }//GEN-LAST:event_btn_selecionar2ActionPerformed

    private void tb_vendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_vendaMouseClicked

    }//GEN-LAST:event_tb_vendaMouseClicked

    private void txt_precoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precoTotalActionPerformed

    private void txt_precoUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precoUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precoUnitActionPerformed

    private void txt_qteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qteActionPerformed

    private void txt_idProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idProdutoActionPerformed

    private void btn_modalProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modalProdutoActionPerformed
        // TODO add your handling code here:
        carregarProdutos();
        dialog_produto.setVisible(true);
        dialog_produto.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_modalProdutoActionPerformed

    private void txt_descricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descricaoActionPerformed

    private void btn_modalClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modalClienteActionPerformed
        // TODO add your handling code here:
        carregarClientes();
        dialog_cliente.setVisible(true);
        dialog_cliente.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_modalClienteActionPerformed

    private void txt_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_clienteActionPerformed

    private void txt_idCLienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idCLienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idCLienteActionPerformed

    private void txt_idVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idVendedorActionPerformed

    private void txt_vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vendedorActionPerformed

    private void btn_modalVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modalVendedorActionPerformed
        carregarVendedores();
        dialog_vendedor.setVisible(true);
        dialog_vendedor.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_modalVendedorActionPerformed

    private void tb_vendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_vendedorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_vendedorMouseClicked

    private void txt_filtro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filtro3ActionPerformed
       // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_filtro3ActionPerformed

    private void txt_filtro3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtro3KeyReleased
        String filtro = txt_filtro3.getText();

                if (filtro.isEmpty()) {
                    carregarVendedores("");
                } else {
                    carregarVendedores(filtro);
        }
    }//GEN-LAST:event_txt_filtro3KeyReleased

    private void btn_selecionar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selecionar3ActionPerformed
        // TODO add your handling code here:
        txt_idVendedor.setText(tb_vendedor.getValueAt(tb_vendedor.getSelectedRow(), 0).toString());
        txt_vendedor.setText(tb_vendedor.getValueAt(tb_vendedor.getSelectedRow(), 1).toString());
        vendedor = new Vendedor();
        vendedor.setId(Integer.parseInt(txt_idVendedor.getText()));
        vendedor.setNome(txt_vendedor.getText());
        dialog_vendedor.dispose();
    }//GEN-LAST:event_btn_selecionar3ActionPerformed

    private void txt_qteCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_qteCaretUpdate
        // TODO add your handling code here:
        txt_precoTotal.setText(String.valueOf(Double.valueOf(txt_qte.getText()) * Double.valueOf(txt_precoUnit.getText())));
    }//GEN-LAST:event_txt_qteCaretUpdate

    private void bt_addProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addProdutoActionPerformed
        itensVenda = new ItensVenda();
        if (txt_idProduto.getText().isEmpty() || txt_descricao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txt_qte.getText().isEmpty()) { //|| txt_qte.getText().isEmpty() || txt_descricao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a quantidade para adicionar o produto.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        itensVenda.setProduto(produto);
        itensVenda.setPreco(Double.valueOf(txt_precoUnit.getText()));
        itensVenda.setQuantidade(Integer.valueOf(txt_qte.getText()));
        itensVenda.setPrecototalitem(Double.valueOf(txt_precoTotal.getText()));
        venda.getItensVenda().add(itensVenda);
        atualizaTabelaItens();
        label_TotVenda.setText(String.valueOf(totalVenda()));
        
        //limpa
        txt_precoUnit.setText("");
        txt_precoTotal.setText("");
        txt_idProduto.setText("");
        txt_descricao.setText("");
        txt_qte.setText("");
    }//GEN-LAST:event_bt_addProdutoActionPerformed

    private void bt_delProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_delProdutoActionPerformed
        // TODO add your handling code here:
        venda.getItensVenda().remove(tb_venda.getSelectedRow());
        atualizaTabelaItens();
        label_TotVenda.setText(String.valueOf(totalVenda()));
    }//GEN-LAST:event_bt_delProdutoActionPerformed

    private void btn_FinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FinalizarVendaActionPerformed
        if (vendedor == null || vendedor.getNome() == null || vendedor.getNome().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um vendedor antes de finalizar a venda.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (cliente == null || cliente.getCliNome() == null || cliente.getCliNome().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente antes de finalizar a venda.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (venda.getItensVenda() == null || venda.getItensVenda().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Adicione pelo menos um produto antes de finalizar a venda.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String totalText = label_TotVenda.getText().trim();
        if (totalText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O total da venda não pode estar vazio.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            venda.setCliente(cliente);
            venda.setVendedor(vendedor);
            double totalVenda = Double.parseDouble(totalText.replace(",", ".")); // Substitui vírgula por ponto se necessário
            venda.setTotalVenda(totalVenda);
            vendaDAO.Salvar(venda);
            JOptionPane.showMessageDialog(null, "Venda finalizada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            
            //TODO desenvolver a limpeza dos campos para uma nova venda
            //      -limpando cliente, vendedor, produto, label_total
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "O valor total da venda é inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            Logger.getLogger(ViewVenda.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "Erro ao salvar a venda: " + e.getMessage(), "Erro no banco de dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_FinalizarVendaActionPerformed

    
    public void atualizaTabelaItens() 
    {
        String dados[][] = new String[venda.getItensVenda().size()][4];
        int i = 0;
        for (ItensVenda iv : venda.getItensVenda ()) {
            dados[i][0] = iv.getProduto().getNome();
            dados[i][1] = String.valueOf(iv.getQuantidade());
            dados[i][2] = String.valueOf(iv.getPreco());
            dados[i][3] = String.valueOf(iv.getPrecototalitem());
            i++;
        }
        String tituloColuna[] = {"Produto", "Quantidade", "Preço Unit", "Preço Total"};
        DefaultTableModel tabelaItens = new DefaultTableModel();
        tabelaItens.setDataVector(dados, tituloColuna);
        
        tb_venda.setModel(new DefaultTableModel(dados, tituloColuna) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };
        
            public boolean isCellEditable (int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
         });
        tb_venda.getColumnModel().getColumn(0).setPreferredWidth(300);
        tb_venda.getColumnModel().getColumn(1).setPreferredWidth(300);
        tb_venda.getColumnModel().getColumn(2).setPreferredWidth(300);
        tb_venda.getColumnModel().getColumn(3).setPreferredWidth(300);
        
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        tb_venda.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        tb_venda.setRowHeight(25);
        tb_venda.updateUI();
    }
            
    private double totalVenda() {
        double total = 0;
        for(ItensVenda item : venda.getItensVenda()) {
            total += item.getPrecototalitem();
        }
        return total;
    }
    
    public void carregarProdutos() {
        try {
            listaModelProdutos = produtoDAO.listarTodosProdutos();
            DefaultTableModel modelo = (DefaultTableModel) tb_produto.getModel();
            modelo.setNumRows(0);           

            for (Produto produto : listaModelProdutos) {
                modelo.addRow(new Object[]{
                    produto.getId(),
                    produto.getNome(),
                    produto.getPreco_venda(),
                    produto.getValidade(),
                    produto.getAno_faixa(),
                    produto.getModelo_carro(),
                    produto.getQuantidade(),
                    produto.getPreco_compra(),
                    produto.getMarca()
                });            
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar produtos: " + e.getMessage());
        }
    }
    
    public void carregarProdutos(String filtro) {
    try {
        ArrayList<Produto> listaProdutos;

        if (filtro.isEmpty()) {
            // Chama o método que retorna todos os produtos
            listaProdutos = produtoDAO.listarTodosProdutos();
        } else {
            // Chama o método de busca com filtro
            listaProdutos = produtoDAO.buscarProduto(filtro);
        }

        DefaultTableModel modelo = (DefaultTableModel) tb_produto.getModel();
        modelo.setNumRows(0); // Limpa a tabela

        // Preenche a tabela com os dados da lista
        for (Produto produto : listaProdutos) {
            modelo.addRow(new Object[]{
                produto.getId(),
                produto.getNome(),
                produto.getPreco_venda(),
                produto.getValidade(),
                produto.getAno_faixa(),
                produto.getModelo_carro(),
                produto.getQuantidade(),
                produto.getPreco_compra(),
                produto.getMarca()
            });
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar produtos: " + e.getMessage());
    }
}
    
    public void carregarClientes() {
        try {
            listaModelClientes = clienteDAO.listarTodosClientes();
            DefaultTableModel modelo = (DefaultTableModel) tb_cliente.getModel();
            modelo.setNumRows(0);           

            for (Cliente cliente : listaModelClientes) {
                modelo.addRow(new Object[]{
                    cliente.getIdCliente(),
                    cliente.getCliNome(),
                    cliente.getCliCpf(),
                    cliente.getCliTelefone()
                });            
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar clientes: " + e.getMessage());
    }
}
    
    public void carregarClientes(String filtro) {
      try {
          ArrayList<Cliente> lista;

          if (filtro.isEmpty()) {
              // Chama o método que retorna todos
              lista = clienteDAO.listarTodosClientes();
          } else {
              // Chama o método de busca com filtro
              lista = clienteDAO.buscarCliente(filtro);
          }

          DefaultTableModel modelo = (DefaultTableModel) tb_cliente.getModel();
          modelo.setNumRows(0); // Limpa a tabela

          // Preenche a tabela com os dados da lista
          for (Cliente cliente : lista) {
                  modelo.addRow(new Object[]{
                      cliente.getIdCliente(),
                      cliente.getCliNome(),
                      cliente.getCliCpf(),
                      cliente.getCliTelefone()
                  });            
          }
      } catch (SQLException e) {
          JOptionPane.showMessageDialog(this, "Erro ao carregar clientes: " + e.getMessage());
        }
    }
    
    public void carregarVendedores() {
        try {
            listaModelVendedores = vendedorDAO.listarTodos();
            DefaultTableModel modelo = (DefaultTableModel) tb_vendedor.getModel();
            modelo.setNumRows(0);           

            for (Vendedor vendedor : listaModelVendedores) {
                modelo.addRow(new Object[]{
                    vendedor.getId(),
                    vendedor.getNome(),
                    vendedor.getCpf()
                });            
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar vendedores: " + e.getMessage());
    }
}
    
    public void carregarVendedores(String filtro) {
      try {
          ArrayList<Vendedor> lista;

          if (filtro.isEmpty()) {
              // Chama o método que retorna todos
              lista = vendedorDAO.listarTodos();
          } else {
              // Chama o método de busca com filtro
              lista = vendedorDAO.buscarVendedor(filtro);
          }

          DefaultTableModel modelo = (DefaultTableModel) tb_vendedor.getModel();
          modelo.setNumRows(0); // Limpa a tabela

          // Preenche a tabela com os dados da lista
          for (Vendedor vendedor : lista) {
                  modelo.addRow(new Object[]{
                      vendedor.getId(),
                      vendedor.getNome(),
                      vendedor.getCpf()
                  });            
          }
      } catch (SQLException e) {
          JOptionPane.showMessageDialog(this, "Erro ao carregar vendedores: " + e.getMessage());
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addProduto;
    private javax.swing.JButton bt_delProduto;
    private javax.swing.JButton btn_FinalizarVenda;
    private javax.swing.JButton btn_modalCliente;
    private javax.swing.JButton btn_modalProduto;
    private javax.swing.JButton btn_modalVendedor;
    private javax.swing.JButton btn_selecionar;
    private javax.swing.JButton btn_selecionar2;
    private javax.swing.JButton btn_selecionar3;
    private javax.swing.JDialog dialog_cliente;
    private javax.swing.JDialog dialog_produto;
    private javax.swing.JDialog dialog_vendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_TotVenda;
    private javax.swing.JLabel label_TotVenda1;
    private javax.swing.JLabel lb_cidade2;
    private javax.swing.JLabel lb_cidade3;
    private javax.swing.JLabel lb_cidade4;
    private javax.swing.JTable tb_cliente;
    private javax.swing.JTable tb_produto;
    private javax.swing.JTable tb_venda;
    private javax.swing.JTable tb_vendedor;
    private javax.swing.JTextField txt_cliente;
    private javax.swing.JTextField txt_descricao;
    private javax.swing.JTextField txt_filtro;
    private javax.swing.JTextField txt_filtro2;
    private javax.swing.JTextField txt_filtro3;
    private javax.swing.JTextField txt_idCLiente;
    private javax.swing.JTextField txt_idProduto;
    private javax.swing.JTextField txt_idVendedor;
    private javax.swing.JTextField txt_precoTotal;
    private javax.swing.JTextField txt_precoUnit;
    private javax.swing.JTextField txt_qte;
    private javax.swing.JTextField txt_vendedor;
    // End of variables declaration//GEN-END:variables
}
