/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author rodri
 */
public class ViewVendas extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ViewVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txt_pesquisa = new javax.swing.JLabel();
        lb_pesquisa = new javax.swing.JTextField();
        btn_pesquisa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_vendas = new javax.swing.JTable();
        bt_excluir = new javax.swing.JButton();
        bt_alterar = new javax.swing.JButton();
        bt_imprimir = new javax.swing.JButton();
        Painel_Cadastro = new javax.swing.JPanel();
        lb_codigo_cliente = new javax.swing.JTextField();
        txt_codigo_cliente = new javax.swing.JLabel();
        txt_nome_cliente = new javax.swing.JLabel();
        lb_numero_venda = new javax.swing.JTextField();
        txt_numero_venda = new javax.swing.JLabel();
        txt_codigo_produto = new javax.swing.JLabel();
        lb_codigo_produto = new javax.swing.JTextField();
        lb_quantidade = new javax.swing.JTextField();
        txt_quantidade = new javax.swing.JLabel();
        bt_adicionarprod = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ProdutosVenda = new javax.swing.JTable();
        bt_cancelar = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        bt_Novo = new javax.swing.JButton();
        lb_valor_total = new javax.swing.JTextField();
        lb_observacao = new javax.swing.JTextField();
        txt_valor_total = new javax.swing.JLabel();
        txt_observacao = new javax.swing.JLabel();
        txt_nome_produto = new javax.swing.JLabel();
        bt_remove_produto = new javax.swing.JButton();
        cbb_nome_produto = new componentes.UJComboBox();
        cbb_nome_cliente = new componentes.UJComboBox();
        lb_desconto = new javax.swing.JTextField();
        txt_desconto = new javax.swing.JLabel();
        txt_data = new javax.swing.JLabel();
        lb_data = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_pesquisa.setText("Pesquisa:");

        btn_pesquisa.setText("Pesquisar");

        tb_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome Cliente", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_vendas);

        bt_excluir.setText("Excluir");
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        bt_alterar.setText("Alterar");
        bt_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarActionPerformed(evt);
            }
        });

        bt_imprimir.setText("Imprimir");
        bt_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pesquisa)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lb_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_pesquisa)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_alterar)
                        .addGap(345, 345, 345)
                        .addComponent(bt_imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_pesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_excluir)
                    .addComponent(bt_alterar)
                    .addComponent(bt_imprimir))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consultar/Excluir/Alterar", jPanel2);

        Painel_Cadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_codigo_cliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lb_codigo_clienteFocusLost(evt);
            }
        });
        Painel_Cadastro.add(lb_codigo_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 79, -1));

        txt_codigo_cliente.setText("Código Cli.");
        Painel_Cadastro.add(txt_codigo_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        txt_nome_cliente.setText("Nome do Cliente:");
        Painel_Cadastro.add(txt_nome_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 11, -1, -1));

        lb_numero_venda.setBackground(new java.awt.Color(204, 255, 204));
        Painel_Cadastro.add(lb_numero_venda, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 31, 158, -1));

        txt_numero_venda.setText("Número da venda:");
        Painel_Cadastro.add(txt_numero_venda, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 11, -1, -1));

        txt_codigo_produto.setText("Código Prod.");
        Painel_Cadastro.add(txt_codigo_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lb_codigo_produto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lb_codigo_produtoFocusLost(evt);
            }
        });
        Painel_Cadastro.add(lb_codigo_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 79, -1));
        Painel_Cadastro.add(lb_quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 130, -1));

        txt_quantidade.setText("Quantidade:");
        Painel_Cadastro.add(txt_quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        bt_adicionarprod.setText("Adicionar");
        bt_adicionarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_adicionarprodActionPerformed(evt);
            }
        });
        Painel_Cadastro.add(bt_adicionarprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 80, -1));

        tb_ProdutosVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Prod.", "Nome Produto", "Quant.", "Valor Un.", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_ProdutosVenda);

        Painel_Cadastro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 663, 271));

        bt_cancelar.setText("Cancelar");
        Painel_Cadastro.add(bt_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        bt_salvar.setText("Salvar");
        bt_salvar.setEnabled(false);
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });
        Painel_Cadastro.add(bt_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, -1, -1));

        bt_Novo.setText("Novo");
        bt_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_NovoActionPerformed(evt);
            }
        });
        Painel_Cadastro.add(bt_Novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));
        Painel_Cadastro.add(lb_valor_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 125, -1));

        lb_observacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lb_observacaoFocusLost(evt);
            }
        });
        Painel_Cadastro.add(lb_observacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 280, 50));

        txt_valor_total.setText("Valor total:");
        Painel_Cadastro.add(txt_valor_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        txt_observacao.setText("Observação:");
        Painel_Cadastro.add(txt_observacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        txt_nome_produto.setText("Nome do Produto:");
        Painel_Cadastro.add(txt_nome_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        bt_remove_produto.setText("Remover Produtos");
        bt_remove_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_remove_produtoActionPerformed(evt);
            }
        });
        Painel_Cadastro.add(bt_remove_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, -1));

        cbb_nome_produto.setAutocompletar(true);
        cbb_nome_produto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbb_nome_produtoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbb_nome_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_nome_produtoActionPerformed(evt);
            }
        });
        Painel_Cadastro.add(cbb_nome_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 340, -1));

        cbb_nome_cliente.setAutocompletar(true);
        cbb_nome_cliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbb_nome_clientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        Painel_Cadastro.add(cbb_nome_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 400, -1));

        lb_desconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lb_descontoFocusLost(evt);
            }
        });
        Painel_Cadastro.add(lb_desconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 111, -1));

        txt_desconto.setText("Desconto:");
        Painel_Cadastro.add(txt_desconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        txt_data.setText("Data:");
        Painel_Cadastro.add(txt_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        lb_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lb_dataFocusLost(evt);
            }
        });
        Painel_Cadastro.add(lb_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 111, -1));

        jTabbedPane1.addTab("Cadastro", Painel_Cadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_codigo_clienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lb_codigo_clienteFocusLost
        // TODO add your handling code here:
        modelCliente = controllerCliente.getClienteController(Integer.parseInt(lb_codigo_cliente.getText()));
        cbb_nome_cliente.setSelectedItem(modelCliente.getCliNome());
    }//GEN-LAST:event_lb_codigo_clienteFocusLost

    private void lb_codigo_produtoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lb_codigo_produtoFocusLost
        // TODO add your handling code here:
        modelProdutos = controllerProdutos.retornarProdutoController(Integer.parseInt(lb_codigo_produto.getText()));
        cbb_nome_produto.setSelectedItem(modelProdutos.getProNome());
    }//GEN-LAST:event_lb_codigo_produtoFocusLost

    private void bt_adicionarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_adicionarprodActionPerformed
        // TODO add your handling code here:
        if (lb_quantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Você deve preencher todos os campos!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            modelProdutos = controllerProdutos.retornarProdutoController(Integer.parseInt(lb_codigo_produto.getText()));
            //adicionar uma linha na tabela
            DefaultTableModel modelo = (DefaultTableModel) tb_ProdutosVenda.getModel();
            int cont = 0;
            double quantidade = 0;
            quantidade = Double.parseDouble(lb_quantidade.getText());
            for (int i = 0; i < cont; i++) {
                modelo.setNumRows(0);
            }

            modelo.addRow(new Object[]{
                modelProdutos.getIdProduto(),
                modelProdutos.getProNome(),
                lb_quantidade.getText(),
                modelProdutos.getProValor(),
                quantidade * modelProdutos.getProValor()
            });
            somarValorTotalProdutos();
        }
    }//GEN-LAST:event_bt_adicionarprodActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        // TODO add your handling code here:
        int codigoVenda = 0, codigoProduto = 0;
        double desconto = 0;
        listaModelVendasProdutoses = new ArrayList<>();

        if (lb_observacao.getText().equals("")) {
            desconto = 0;
        } else {
            desconto = Double.parseDouble(lb_observacao.getText());
        }
        if (!lb_numero_venda.getText().equals("")) {
            modelVendas.setIdVenda(Integer.parseInt(lb_numero_venda.getText()));
        }
        modelVendas.setCliente(Integer.parseInt(lb_codigo_cliente.getText()));
        try {
            modelVendas.setVenDataVenda(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception e) {
        }
        modelVendas.setVenValorLiquido(Double.parseDouble(lb_valor_total.getText()));
        modelVendas.setVenValorBruto(Double.parseDouble(lb_valor_total.getText()) + desconto);

        modelVendas.setVenDesconto(desconto);

        if (alterarSalvar.equals("salvar")) {
            //salva
            codigoVenda = controllerVendas.salvarVendasController(modelVendas);
            if (codigoVenda > 0) {
                JOptionPane.showMessageDialog(this, "Venda salva com sucesso", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar a venda", "Erro", JOptionPane.ERROR_MESSAGE);
            }

            int cont = tb_ProdutosVenda.getRowCount();
            for (int i = 0; i < cont; i++) {
                codigoProduto = (int) tb_ProdutosVenda.getValueAt(i, 0);
                modelVendasProdutos = new ModelVendasProdutos();
                modelProdutos = new ModelProdutos();
                modelVendasProdutos.setProduto(codigoProduto);
                modelVendasProdutos.setVendas(codigoVenda);
                modelVendasProdutos.setVenProValor((double) tb_ProdutosVenda.getValueAt(i, 3));
                modelVendasProdutos.setVenProQuantidade(Integer.parseInt(tb_ProdutosVenda.getValueAt(i, 2).toString()));
                //produto
                modelProdutos.setIdProduto(codigoProduto);
                modelProdutos.setProEstoque(controllerProdutos.retornarProdutoController(codigoProduto).getProEstoque()
                    - Integer.parseInt(tb_ProdutosVenda.getValueAt(i, 2).toString()));
                listaModelVendasProdutoses.add(modelVendasProdutos);
                listaModelProdutoses.add(modelProdutos);
            }
            //Salvar os produtos da venda
            if (controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutoses)) {
                //alterar o estoque de produtos
                controllerProdutos.alterarEstoqueProdutoController(listaModelProdutoses);
                //                JOptionPane.showMessageDialog(this, "produtos da venda salvo com sucesso", "Atenção", JOptionPane.WARNING_MESSAGE);
                carregarVendas();
                limparFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar a produtos", "Erro", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            //altera
            //INICIO RETORNAR PARA O ESTOQUE E EXCLUIR PRODUTOS DA VENDA
            int linha = tb_vendas.getSelectedRow();
            codigoVenda = (int) tb_vendas.getValueAt(linha, 0);
            listaModelProdutoses = new ArrayList<>();
            listaModelProdutosVendasProdutoses = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(codigoVenda);
            for (int i = 0; i < listaModelProdutosVendasProdutoses.size(); i++) {
                modelProdutos = new ModelProdutos();
                modelProdutos.setIdProduto(listaModelProdutosVendasProdutoses.get(i).getModelProdutos().getIdProduto());
                modelProdutos.setProEstoque(
                    listaModelProdutosVendasProdutoses.get(i).getModelProdutos().getProEstoque()
                    + listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVenProQuantidade());
                listaModelProdutoses.add(modelProdutos);
            }
            if (controllerProdutos.alterarEstoqueProdutoController(listaModelProdutoses)) {
                if (controllerVendasProdutos.excluirVendasProdutosController(codigoVenda)) {
                    this.carregarVendas();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir a venda", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir a venda", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            //FIM RETORNAR PARA O ESTOQUE E EXCLUIR PRODUTOS DA VENDA

            if (controllerVendas.atualizarVendasController(modelVendas)) {
                JOptionPane.showMessageDialog(this, "Venda alterada com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar a venda", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            //adicionar produtos na lista para salvar
            int cont = tb_ProdutosVenda.getRowCount();
            for (int i = 0; i < cont; i++) {
                codigoProduto = (int) tb_ProdutosVenda.getValueAt(i, 0);
                modelVendasProdutos = new ModelVendasProdutos();
                modelProdutos = new ModelProdutos();
                modelVendasProdutos.setProduto(codigoProduto);
                modelVendasProdutos.setVendas(codigoVenda);
                modelVendasProdutos.setVenProValor((double) tb_ProdutosVenda.getValueAt(i, 3));
                modelVendasProdutos.setVenProQuantidade(Integer.parseInt(tb_ProdutosVenda.getValueAt(i, 2).toString()));
                //produto
                modelProdutos.setIdProduto(codigoProduto);
                modelProdutos.setProEstoque(controllerProdutos.retornarProdutoController(codigoProduto).getProEstoque()
                    - Integer.parseInt(tb_ProdutosVenda.getValueAt(i, 2).toString()));
                listaModelVendasProdutoses.add(modelVendasProdutos);
                listaModelProdutoses.add(modelProdutos);
            }
            //salvar os produtos da venda
            if (controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutoses)) {
                controllerProdutos.alterarEstoqueProdutoController(listaModelProdutoses);
                carregarVendas();
                limparFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar a produtos", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        bt_salvar.setEnabled(false);
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_NovoActionPerformed
        // TODO add your handling code here
        bt_salvar.setEnabled(true);
        alterarSalvar = "salvar";
        limparFormulario();
    }//GEN-LAST:event_bt_NovoActionPerformed

    private void lb_observacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lb_observacaoFocusLost
        // TODO add your handling code here:
        somarValorTotalProdutos();
    }//GEN-LAST:event_lb_observacaoFocusLost

    private void bt_remove_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_remove_produtoActionPerformed
        // TODO add your handling code here:
        int linha = tb_ProdutosVenda.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tb_ProdutosVenda.getModel();
        modelo.removeRow(linha);
        somarValorTotalProdutos();
    }//GEN-LAST:event_bt_remove_produtoActionPerformed

    private void cbb_nome_produtoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbb_nome_produtoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (cbb_nome_produto.isVisible()) {
            preencherCodigoProdutoPeloCombobox();
        }
    }//GEN-LAST:event_cbb_nome_produtoPopupMenuWillBecomeInvisible

    private void cbb_nome_clientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbb_nome_clientePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (cbb_nome_cliente.isPopupVisible()) {
            preencherCodigoClientePeloCombobox();
        }
    }//GEN-LAST:event_cbb_nome_clientePopupMenuWillBecomeInvisible

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        // TODO add your handling code here:
        int linha = tb_vendas.getSelectedRow();
        int codigoVenda = (int) tb_vendas.getValueAt(linha, 0);
        listaModelProdutoses = new ArrayList<>();
        listaModelProdutosVendasProdutoses = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(codigoVenda);
        for (int i = 0; i < listaModelProdutosVendasProdutoses.size(); i++) {
            modelProdutos = new ModelProdutos();
            modelProdutos.setIdProduto(listaModelProdutosVendasProdutoses.get(i).getModelProdutos().getIdProduto());
            modelProdutos.setProEstoque(
                listaModelProdutosVendasProdutoses.get(i).getModelProdutos().getProEstoque()
                + listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVenProQuantidade());
            listaModelProdutoses.add(modelProdutos);
        }
        if (controllerProdutos.alterarEstoqueProdutoController(listaModelProdutoses)) {
            controllerVendasProdutos.excluirVendasProdutosController(codigoVenda);
            if (controllerVendas.excluirVendasController(codigoVenda)) {
                JOptionPane.showMessageDialog(this, "Venda excluida com sucesso", "Atenção", JOptionPane.WARNING_MESSAGE);
                this.carregarVendas();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir a venda", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir a venda", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void bt_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarActionPerformed
        // TODO add your handling code here:
        //habilitar botão novo para alterar
        bt_salvar.setEnabled(true);
        //setar variavel alterar salvar´para alterar
        alterarSalvar = "alterar";
        int linha = tb_vendas.getSelectedRow();
        int codigoVenda = (int) tb_vendas.getValueAt(linha, 0);
        listaModelProdutosVendasProdutoses = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(codigoVenda);
        DefaultTableModel modelo = (DefaultTableModel) tb_ProdutosVenda.getModel();
        modelo.setNumRows(0);
        for (int i = 0; i < listaModelProdutosVendasProdutoses.size(); i++) {
            lb_numero_venda.setText(String.valueOf(listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVendas()));
            modelo.addRow(new Object[]{
                listaModelProdutosVendasProdutoses.get(i).getModelProdutos().getIdProduto(),
                listaModelProdutosVendasProdutoses.get(i).getModelProdutos().getProNome(),
                listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVenProQuantidade(),
                listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVenProValor(),
                listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVenProQuantidade()
                * listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVenProValor()
            });
        }
        somarValorTotalProdutos();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_bt_alterarActionPerformed

    private void bt_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imprimirActionPerformed
        int linha = tb_vendas.getSelectedRow();
        int codigoVenda = (int) tb_vendas.getValueAt(linha, 0);
        final ViewAguarde carregando = new ViewAguarde();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {
                //metodo de impimir
                try {
                    controllerVendas.gerarRelatorioVenda(codigoVenda);
                    carregando.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao gerar o relatório! /n " + e, "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }

        };
        t.start();
    }//GEN-LAST:event_bt_imprimirActionPerformed

    private void lb_descontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lb_descontoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_descontoFocusLost

    private void lb_dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lb_dataFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_dataFocusLost

    private void cbb_nome_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_nome_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_nome_produtoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Cadastro;
    private javax.swing.JButton bt_Novo;
    private javax.swing.JButton bt_adicionarprod;
    private javax.swing.JButton bt_alterar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_imprimir;
    private javax.swing.JButton bt_remove_produto;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JButton btn_pesquisa;
    private componentes.UJComboBox cbb_nome_cliente;
    private componentes.UJComboBox cbb_nome_produto;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lb_codigo_cliente;
    private javax.swing.JTextField lb_codigo_produto;
    private javax.swing.JTextField lb_data;
    private javax.swing.JTextField lb_desconto;
    private javax.swing.JTextField lb_numero_venda;
    private javax.swing.JTextField lb_observacao;
    private javax.swing.JTextField lb_pesquisa;
    private javax.swing.JTextField lb_quantidade;
    private javax.swing.JTextField lb_valor_total;
    private javax.swing.JTable tb_ProdutosVenda;
    private javax.swing.JTable tb_vendas;
    private javax.swing.JLabel txt_codigo_cliente;
    private javax.swing.JLabel txt_codigo_produto;
    private javax.swing.JLabel txt_data;
    private javax.swing.JLabel txt_desconto;
    private javax.swing.JLabel txt_nome_cliente;
    private javax.swing.JLabel txt_nome_produto;
    private javax.swing.JLabel txt_numero_venda;
    private javax.swing.JLabel txt_observacao;
    private javax.swing.JLabel txt_pesquisa;
    private javax.swing.JLabel txt_quantidade;
    private javax.swing.JLabel txt_valor_total;
    // End of variables declaration//GEN-END:variables
}
